### ISSUE TITLE
Requested Navigation Improvements

### ISSUE THREAD

**Issue by rptomey** [rrnarayan1/omni-crosswords#1]
The app is lovely so far, and it's very encouraging to see that it's being actively worked on. Not sure whether you'll see this, but I have a couple of requests for improving the navigation while you're in the puzzles.

1. Currently, when you hit the left or right arrows to navigate to the next word, the cursor always goes to the first letter in the word, even if you've already filled it in. Instead, I would expect it to go to the first blank cell.
2. When you're typing in a partially completed word, it should loop back when you reach the end if there are still unfilled cells. For example, I knew _P_D was going to be "IPOD". When I filled in the "O", it took me to the next word instead of back to the blank cell at the beginning.
3. More of a nice to have, but would love the option of using swipe gestures to navigate. Ideally the following swipe behaviors:
* When viewing an across word, swiping horizontally goes to either the next or previous across.
* When viewing a down word, swiping vertically goes to either the next or previous down.
* When swiping vertically while viewing an across or swiping horizontally while viewing a down, stay in the current cell, but toggle to down or across, respectively.

**Comment by samsrabin** [comment]
+1 for 1 and 2, which would help the app behave more like the NYT app. That difference is something that consistently prevents me from using other crossword apps. An ideal solution for users might be for these behaviors to be optionally enabled.

**Comment by rrnarayan1** [comment]
Sorry @rptomey + @samsrabin , I just saw this today, I don't really monitor the repo on github (mostly because I don't expect much activity from others)

For (1), I believe I addressed this in https://github.com/rrnarayan1/omni-crosswords/commit/6bc43d8eef1a0eed1bf10cd0513f36f0d8113083.

For (2) and (3), I see what you're getting at. I'll add it to the backlog. The looping back inside the word will likely be a setting you have to enable when implemented.

**Comment by rrnarayan1** [comment]
@rptomey + @samsrabin: swiping right and left were enabled in d7f2b8e1830856123c31c17aed781f8d942e0fb0. 
vertical swipes are harder to deal with because it interferes with possible scrolling issues on smaller phones.

**Comment by rrnarayan1** [comment]
Added the setting to loop back inside the word here: 07cb40b63522a1241b4d1b836dc1231379e74f65. Closing this issue now.
By the way, there's a setting to use the space bar to toggle directions - that could help with your other comment.

**Comment by rptomey** [comment]
Tried it today, and the looping works great! Thank you for continuing to
develop this app.
