### ISSUE TITLE
App is down

### ISSUE THREAD

**Issue by agent2397** [rrnarayan1/omni-crosswords#16]
When you open the app it immediately closes. Might be a server issue?

I’ve tried deleting the app and reinstalling. Also have tried on another device. 

Thank you for creating and supporting this app 🙌

**Comment by AmyAmeliaLee** [comment]
Sadly I can confirm this. It seems that the functionality behind uploading/updating the puzzles may be causing this.

**Comment by rrnarayan1** [comment]
This is because of a puzzle metadata issue. When parsing the puzzle to display the list view, the app could crash. I will leave this issue open to address that issue by failing more gracefully.

**Comment by rrnarayan1** [comment]
addressed in b859987
